/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.servidor.Servidor;



public class App {
    public static void main(String[] args) {
        
        Servidor.main(args);
          

        }
    }


